name: "CI"
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{matrix.os}}
    continue-on-error: ${{matrix.emacs_version == 'snapshot'}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        emacs_version: ['26.1', '26.2', '26.3', '27.1', '27.2']

    steps:
    - name: Set up Emacs
      if: "!startsWith (matrix.os, 'windows')"
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Set up Emacs on Windows
      if: startsWith (matrix.os, 'windows')
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop update
        scoop bucket add extras
        scoop install emacs@${{ matrix.emacs_version }}
        echo "$env:PATH" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Set git to use LF
      run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

    - name: Check out this repo source code
      uses: actions/checkout@v2

    - name: Check out the ELDEV source code # until Windows-Support is on melpa@stable
      uses: actions/checkout@v2
      with:
        repository: doublep/eldev
        path: eldev

    - name: Eldev Test
      run: |
        ./eldev/bin/eldev  eval emacs-version
      env:
        ELDEV_LOCAL: "./eldev"
